version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/react"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        applies-to: version-updates
        patterns:
          - "*"
